=== barsie/jounalying_in_programming/ProgrammingAssigment/BookstoreXMLSchema/catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="bookCatalog">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="bookElement" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="bookTitle">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="publicationYear" type="xs:integer" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

              <xs:element name="bookAuthor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="authorFirstName" type="xs:string"/>
                    <xs:element name="authorLastName" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="bookDetails">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="publisher" type="xs:string"/>
                    <xs:element name="pageCount" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>

            <xs:attribute name="bookId" type="xs:string" use="required"/>
            <xs:attribute name="isAvailable" type="xs:boolean" use="required"/>

          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== barsie/jounalying_in_programming/ProgrammingAssigment/BookstoreXMLSchema/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./styles/catalog.xls"?>

<bookCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog.xsd">

  <bookElement bookId="B001" isAvailable="true">
    <bookTitle publicationYear="1925">The Great Gatsby</bookTitle>
    <bookAuthor>
      <authorFirstName>F. Scott</authorFirstName>
      <authorLastName> Fitzgerald</authorLastName>
    </bookAuthor>
    <bookPublisher>
      <publiserName>Toronto Wills</publiserName>
    </bookPublisher>
  </bookElement>

  <bookElement bookId="B002" isAvailable="false">

    <bookTitle publicationYear="1949">Great Seam Book</bookTitle>

    <bookAuthor>
      <authorFirstName>George</authorFirstName>
      <authorLastName> Torneveing</authorLastName>
    </bookAuthor>

    <bookDetails>
      <publisher>Tirant Publication</publisher>
      <pageCount>100</pageCount>
    </bookDetails>

  </bookElement>

    <bookElement bookId="B002" isAvailable="true">

    <bookTitle publicationYear="1949">Austing Torino</bookTitle>

    <bookAuthor>
      <authorFirstName>Vil</authorFirstName>
      <authorLastName> Vinashinmoring</authorLastName>
    </bookAuthor>

    <bookDetails>
      <publisher>Titntu</publisher>
      <pageCount>1800</pageCount>
    </bookDetails>

  </bookElement>

</bookCatalog>
